# Generated by Django 4.0.3 on 2022-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='q', upload_to='images'),
            preserve_default=False,
        ),
    ]
