version: "3"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=skillbox
      - POSTGRES_PASSWORD=skillbox
      - POSTGRES_DB=skillbox
    env_file:
      - ./.env
    ports:
      - 5432

  web:
    build: .
    command:  bash -c "python manage.py makemigrations --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  bot:
    build: .
    command: python run_pooling.py
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - postgres

volumes:
  postgres_data:
